# Generated by Django 5.0.14 on 2025-12-14 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("difficulty_min", models.PositiveSmallIntegerField()),
                ("difficulty_max", models.PositiveSmallIntegerField()),
                ("categories", models.JSONField(default=list)),
                ("prescription", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_instances",
                        to="training.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily exercise",
                "verbose_name_plural": "Daily exercises",
                "ordering": ["scheduled_for", "order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyexercise",
            constraint=models.UniqueConstraint(
                fields=("user", "scheduled_for", "order"),
                name="unique_daily_exercise_order",
            ),
        ),
    ]
