# Generated by Django 5.0.14 on 2025-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyexercise",
            name="repetitions",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyexercise",
            name="sets",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
