# Generated by Django 5.0.14 on 2025-12-14 06:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_exerciselog_exerciselog_unique_exercise_log_per_set"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_for",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("sleep_duration", models.DurationField()),
                (
                    "sleep_quality",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "nutrition",
                    models.CharField(
                        choices=[
                            ("below_average", "Below average"),
                            ("average", "Average"),
                            ("amazing", "Amazing"),
                        ],
                        default="average",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery log",
                "verbose_name_plural": "Recovery logs",
                "ordering": ["-recorded_for", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="recoverylog",
            constraint=models.UniqueConstraint(
                fields=("user", "recorded_for"), name="unique_recovery_log_per_day"
            ),
        ),
    ]
