# Generated by Django 5.0.14 on 2025-12-14 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_recoverylog_recoverylog_unique_recovery_log_per_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FatigueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_for",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("responses", models.JSONField(default=list)),
                ("total_score", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fatigue_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatigue log",
                "verbose_name_plural": "Fatigue logs",
                "ordering": ["-recorded_for", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="fatiguelog",
            constraint=models.UniqueConstraint(
                fields=("user", "recorded_for"), name="unique_fatigue_log_per_day"
            ),
        ),
    ]
