# Generated by Django 5.0.14 on 2025-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_fatiguelog_fatiguelog_unique_fatigue_log_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
