# Generated by Django 5.0.14 on 2025-12-14 22:39

from django.db import migrations, models


def map_nutrition_values_forward(apps, schema_editor):
    RecoveryLog = apps.get_model("training", "RecoveryLog")

    value_map = {
        "amazing": "great",
        "average": "ok",
        "below_average": "poor",
    }

    for old_value, new_value in value_map.items():
        RecoveryLog.objects.filter(nutrition=old_value).update(nutrition=new_value)


def map_nutrition_values_backward(apps, schema_editor):
    RecoveryLog = apps.get_model("training", "RecoveryLog")

    value_map = {
        "great": "amazing",
        "ok": "average",
        "poor": "below_average",
    }

    for old_value, new_value in value_map.items():
        RecoveryLog.objects.filter(nutrition=old_value).update(nutrition=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_exercise_info"),
    ]

    operations = [
        migrations.RunPython(
            map_nutrition_values_forward, reverse_code=map_nutrition_values_backward
        ),
        migrations.AlterField(
            model_name="recoverylog",
            name="nutrition",
            field=models.CharField(
                choices=[("great", "Great"), ("ok", "OK"), ("poor", "Poor")],
                default="ok",
                max_length=20,
            ),
        ),
    ]
